apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: haproxy-ingress
spec:
  rules:
  - host: nginx.k8s.infradigital.com
    http:
      paths:
      - path: "/"
        backend:
          serviceName: nginx
          servicePort: 80
  - host: www.letschat.com
    http:
      paths:
      - path: "/"
        backend:
          serviceName: letschat
          servicePort: 8080
  - host: www.guestbook.com
    http:
      paths:
      - path: "/"
        backend:
          serviceName: frontend
          servicePort: 80
  - host: sql.k8s.infradigital.com
    paths:
    - path: "/"
      backend:
        serviceName: postgres
        servicePort: 5432
