apiVersion: v1
kind: Service
metadata:
  name: postgres
  labels: 
    app: postgres
spec:
  type: ClusterIP
  ports:
    - port: 80
      protocol: TCP
      targetPort: 5432
  selector:
    app: postgres
